app = 'codr-python-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'


[env]
  auto_start_machines = 'true'
  min_machines_running = '0'  

[http_service]
  auto_stop_machines = true


[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1