app = 'codr-python-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'


# Keep worker running
min_machines_running = 0
auto_start_machines = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1