app = 'codr-javascript-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  LANGUAGE = "javascript"

# Keep worker running
min_machines_running = 0
auto_start_machines = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1