# fly.toml app configuration file generated for codr-api on 2025-05-05T13:08:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codr-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'kvm'
  destination = '/dev/kvm'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # WebSocket settings
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  # WebSocket timeouts
  [http_service.timeouts]
    read_timeout = "120s"
    write_timeout = "120s"
    idle_timeout = "120s"
    
  # Additional headers for security
  [[http_service.headers]]
    for = "/*"
    [http_service.headers.values]
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      Content-Security-Policy = "default-src 'self'; connect-src 'self' wss:; script-src 'self'"
      X-XSS-Protection = "1; mode=block"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"
      Referrer-Policy = "no-referrer"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
