# fly.toml app configuration file generated for codr-api on 2025-05-05T13:08:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codr-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'kvm'
  destination = '/dev/kvm'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  auto_stop_grace_period = "30s"
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
