# fly.toml app configuration file generated for codr-java-runner-wild-sun-8691 on 2025-05-07T13:47:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codr-java-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  LANGUAGE = 'java'
  auto_start_machines = 'true'
  min_machines_running = '1'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
