
app = 'codr-sandbox-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

# Increased resources for Firecracker
[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

# Mount required for KVM
[mounts]
  source = "kvm"
  destination = "/dev/kvm"
