app = 'codr-sandbox-worker'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  REDIS_URL = "rediss://:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}"