# fly.toml app configuration file generated for codr-c-runner on 2025-05-05T22:02:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codr-c-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  auto_start_machines = 'true'
  min_machines_running = '0'  

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
