app = 'codr-c-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  REDIS_HOST = "factual-tuna-22307.upstash.io"
  REDIS_PORT = "6379"
  REDIS_PASS = "AVcjAAIjcDE1N2NkNWJiOTYyNzE0ZGZjOGNkZDYwNGI1ZTRmYTFiOXAxMA"
  ORIGINS = "https://localhost"
  LANGUAGE = "c"
  MAX_EXECUTION_TIME = "3"
  MAX_MEMORY_MB = "100"

# Keep worker running
min_machines_running = 1
auto_start_machines = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

