# fly.toml app configuration file generated for codr-cpp-runner on 2025-05-05T23:10:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codr-cpp-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  auto_start_machines = 'true'
  min_machines_running = '0'  

[http_service]
  auto_stop_machines = true


[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
