app = 'codr-rust-runner'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

# Keep worker running
min_machines_running = 1
auto_start_machines = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1